TARGET_FOLDER_PATH=C:\\Users\\OLI\\Desktop\\Home
SERVER_PORT=50051
SERVER_CERT_FILE_PATH=./resources/certs/local-sync-server.crt
SERVER_KEY_FILE_PATH=./resources/certs/local-sync-server.key
CLIENT_CA_CERT_FILE_PATH=./resources/certs/local-sync-ca.crt